image: infoware/gitlab-ci-android

variables:
  DOCKER_DRIVER: overlay2
  WORKSPACE: ${CI_PROJECT_DIR}
  PIPELINE_ID: ${CI_PIPELINE_ID}



stages:
  - build_and_test

before_script:
  - export GRADLE_USER_HOME=$(pwd)/.gradle
  - chmod +x gradlew

build_and_test:
  stage: build_and_test
  script:
    - ./gradlew clean assemble
    - ./gradlew test
  tags:
    - android
  artifacts:
    paths:
      - app/build
    expire_in: 1 day
